import os
from enum import Enum

TOKEN = os.environ.get("BOT_TOKEN")

WHITE_LIST = {
    "kimtabris": "Nikita"
}

HANDLERS = (
    "middleware",
    "entry",
)

REDIS_HOST = "localhost"
REDIS_PORT = 6379


class State(Enum):
    IN_MAIN_MENU = 1

    START_RESERVATION_CREATE = 2
    CHOOSING_RESERVATION_DATE_CREATE = 3
    CHOOSING_RESERVATION_WORKSPACE_CREATE = 4
    SUCCESS_CREATE = 5

    START_RESERVATION_READ = 6
    CHOOSING_RESERVATION_DATE_READ = 7
    SUCCESS_READ = 8

    START_RESERVATION_DELETE = 9
    CHOOSING_RESERVATION_DATE_DELETE = 10
    SUCCESS_DELETE = 11


EXIT_MESSAGE = "exit"


RESERVATIONS_STATES_CREATE = (
    State.START_RESERVATION_CREATE,
    State.CHOOSING_RESERVATION_DATE_CREATE,
    State.CHOOSING_RESERVATION_WORKSPACE_CREATE,
    State.SUCCESS_CREATE
)

RESERVATIONS_STATES_READ = (
    State.START_RESERVATION_READ,
    State.CHOOSING_RESERVATION_DATE_READ,
    State.SUCCESS_READ,
)

RESERVATIONS_STATES_DELETE = (
    State.START_RESERVATION_DELETE,
    State.CHOOSING_RESERVATION_DATE_DELETE,
    State.SUCCESS_DELETE,
)
